FROM adoptopenjdk:11-jre-hotspot
ARG JARNAME=expert-consultation-0.0.1-SNAPSHOT.jar
WORKDIR /opt
COPY target/$JARNAME /opt/expert-consultation.jar
EXPOSE 8080
CMD ["java", "-jar", "/opt/expert-consultation.jar", "--spring.profiles.active=production"]
